name: Build and push docker image to docker Hub

on: push
jobs: 
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v3

      - name: login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrete.DOCKERHUB_USERNAME }}
          password: ${{ secrete.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          registory: docker.io
          image: kdua1/docowens-image
          tags: kdua1/kwakudua:v1, latest     